Traceback (most recent call last):
  File "/Users/bzoennchen/Development/workspaces/python3env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/bzoennchen/Development/workspaces/python3env/lib/python3.9/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/bzoennchen/Development/workspaces/python3env/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/bzoennchen/Development/workspaces/python3env/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bzoennchen/Development/workspaces/python3env/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/bzoennchen/Development/workspaces/python3env/lib/python3.9/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/bzoennchen/Development/workspaces/python3env/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def sieve_of_eratosthenes(N):
    N = 100
    prime_sieve = [True for i in range(N)]
    prime_sieve[0] = False
    prime_sieve[1] = False
    for i in range(2, int(np.sqrt(N))):
        if prime_sieve[i]:
            for j in range(i**2, N, i):
                prime_sieve[j] = False
    
    primes = []
    for i in range(N):
        if prime_sieve[i]:
            primes.append(i)
    return primes
        
sieve_of_eratosthenes(100)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-351987172dea>[0m in [0;36m<module>[0;34m[0m
[1;32m     15[0m     [0;32mreturn[0m [0mprimes[0m[0;34m[0m[0;34m[0m[0m
[1;32m     16[0m [0;34m[0m[0m
[0;32m---> 17[0;31m [0msieve_of_eratosthenes[0m[0;34m([0m[0;36m100[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-1-351987172dea>[0m in [0;36msieve_of_eratosthenes[0;34m(N)[0m
[1;32m      4[0m     [0mprime_sieve[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mprime_sieve[0m[0;34m[[0m[0;36m1[0m[0;34m][0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m     [0;32mfor[0m [0mi[0m [0;32min[0m [0mrange[0m[0;34m([0m[0;36m2[0m[0;34m,[0m [0mint[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0msqrt[0m[0;34m([0m[0mN[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m         [0;32mif[0m [0mprime_sieve[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m             [0;32mfor[0m [0mj[0m [0;32min[0m [0mrange[0m[0;34m([0m[0mi[0m[0;34m**[0m[0;36m2[0m[0;34m,[0m [0mN[0m[0;34m,[0m [0mi[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

